name: Build and Deploy Flutter Web App
on:
  push:
    branches: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: 3.29.2
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web --release
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_branch: main
          publish_dir: ./build/web
          destination_dir: ./ # For deploying to root of Kratosgado.github.io
          external_repository: Kratosgado/Kratosgado.github.io
          keep_files: false
